### PR TITLE
Fixed audio sample playback in README.md.

### PR DESCRIPTION
**Pull request by R-802**
Audio sample links can now be played directly in the browser without requiring a download.

### CODE REVIEW

**Comment by thorstenMueller** [comment]
Thanks for your pull request 😊. It's a good idea to have the samples playable directly in the browser. But when i get it right, the files are loaded from your Github repo. Is there a way to keep the samples inside this repo?

**Comment by thorstenMueller** [comment]
Thank you for adding the audio files. When i see it right, you should adjust the link in README.md too, because it still links to ...
> e.g.: https GITHUB /R-802/Thorsten-Voice/assets/109842181/23ffc3cf-9962-47d9-b28e-2be36f1bcec5

**Comment by R-802** [comment]
Sorry about that, I could not for the life of me figure out how to make the files play in the readme. Somehow these guys (https://github.com/suno-ai/bark) managed to do it using videos with the audio but the video/audio files are not in the repo. Also relinking the files with ./samples/thorsten-21.06-emotional/Mov/neutral.mov... etc does not work so I'll just close the PR.

**Comment by thorstenMueller** [comment]
Sorry to hear that, but i really like your idea. So thank you for trying. Maybe i can give it a try myself in future based on your code/inspiration 👏😊.

**Pull request closed without merging**
